package au.edu.federation.itech3107.fedunimillionaire30339249.data;

import android.util.Log;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.Array;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;

public class QuestionManager {
    public static final String TAG = "QuestionManager";

    private static class DifficultyLevel {
        /**
         * The number of questions before increasing the difficulty level.
         */
        private final int count;
        private final Difficulty difficulty;

        public DifficultyLevel(int count, Difficulty difficulty) {
            this.count = count;
            this.difficulty = difficulty;
        }

    }

    /**
     * A map containing questions of each difficulty level.
     */
    private final Map<Difficulty, List<Question>> questions = new HashMap<>();

    /**
     * A list of difficulty levels, with the number of questions needed until the difficulty level is increased.
     */
    private final List<DifficultyLevel> difficultySequence = new ArrayList<>();

    /**
     * What questions are "safe money" (zero-based)
     */
    private final Set<Integer> safeMoneyIndices = new HashSet<>();

    /**
     * A list of question money values. If more questions are created than defined in this list, the last value will be used.
     */
    private final List<Double> questionValues = new ArrayList<>();


    public QuestionManager() {
    }

    /**
     * Appends the {@link Difficulty} level to be used next for the specified number of questions.
     *
     * @param count the number of questions this difficulty will be used for.
     */
    public void appendDifficultySeq(int count, Difficulty difficulty) {
        difficultySequence.add(new DifficultyLevel(count, difficulty));
    }

    /**
     * Adds the question to this {@link QuestionManager}. Once added it can appear within question sets generated by using {@link #createNextQuestionSet(int)}.
     *
     * @param question the question to add.
     */
    public void addQuestion(Question question) {
        Log.d(TAG, "  - Adding question for difficulty " + question.getDifficulty() + ": " + question.getQuestionText());

        if (questions.containsKey(question.getDifficulty())) {
            questions.get(question.getDifficulty()).add(question); // add into existing list.
        } else {
            List<Question> dQuestions = new ArrayList<>();
            dQuestions.add(question);
            questions.put(question.getDifficulty(), dQuestions);
        }
    }

    /**
     * Load questions from a JSON string. Calls {@link #addQuestion(Question)} for each question parsed. See "questions-easy.json" for schema details.
     * @param json the json text.
     * @throws JSONException if an exception occurs when parsing the JSON string.
     */
    public void loadQuestions(String json) throws JSONException {
        Log.d(TAG, "Loading questions from JSON...");

        JSONObject jRoot = new JSONObject(json);

        JSONArray jQuestions = jRoot.getJSONArray("questions");
        for (int i = 0; i < jQuestions.length(); i++) {
            Question question = new Question(jQuestions.getJSONObject(i));
            addQuestion(question);
        }
    }

    /**
     * Sets what questions are considered "safe money". The specified indices array is zero-based.
     * @param isSafe if true the provided indices as safe, false otherwise.
     * @param indices the array of question indices (zero-based).
     */
    public void setSafeMoneyQuestions(boolean isSafe, int... indices) {
        for (int index : indices) {
            if (isSafe) {
                safeMoneyIndices.add(index);
            } else {
                safeMoneyIndices.remove(index);
            }
        }
    }

    /**
     * Sets the money values for questions. If more questions are created (see {@link #createNextQuestionSet(int)}) than defined in this array, the last value will be used.
     *
     * @param values an array of money values.
     */
    public void setQuestionValues(double... values) {
        questionValues.clear();
        for (double value : values)
            questionValues.add(value);
    }

    /**
     * Returns a list of questions (limited to the specified count) and that follows the difficulty sequence defined in this {@link QuestionManager}
     *
     * @param count The number of questions to return.
     * @return an {@link ArrayList} of questions, or an empty {@link ArrayList} if no difficulty sequence was defined. See {@link QuestionManager#appendDifficultySeq(int, Difficulty)}
     */
    public List<GameQuestion> createNextQuestionSet(int count) {
        int difficultyIndex = 0; // The current difficulty level index.
        int questionsOfCurrentDifficulty = 0; // The number of questions added while at the current difficulty.

        List<GameQuestion> questionList = new ArrayList<>();

        if (difficultySequence.isEmpty())
            return questionList;

        for (int i = 0; i < count; i++) {
            DifficultyLevel level = difficultySequence.get(difficultyIndex);

            // Get all the questions of a current difficulty.
            List<Question> questionsOfDifficulty = questions.get(level.difficulty);

            // Add a random question of the current difficulty to the question list.
            int index = (int) (Math.random() * questionsOfDifficulty.size()); // TODO: Prevent duplicate questions appearing in question "set".

            Question q = questionsOfDifficulty.get(index);
            boolean isSafe = safeMoneyIndices.contains(i);

            // Get the question value, if the explicit question value isn't defined use the last value.
            double value = 0;
            if (!questionValues.isEmpty())
                value = questionValues.get(Math.min(i, questionValues.size() - 1));

            questionList.add(new GameQuestion(q, value, isSafe));

            questionsOfCurrentDifficulty++;

            // We have reached the required number of questions for this difficulty level.
            if (questionsOfCurrentDifficulty == level.count) {
                questionsOfCurrentDifficulty = 0;

                // Goto the next difficulty level in the sequence.
                difficultyIndex = Math.min(difficultyIndex + 1, difficultySequence.size() - 1);
            }

        }
        return questionList;
    }


    /**
     * Clears the difficulty sequence. See {@link #appendDifficultySeq(int, Difficulty)}
     */
    public void clearDifficultySeq() {
        difficultySequence.clear();
    }

    /**
     * Clears all questions loaded in this {@link QuestionManager}. See {@link #addQuestion(Question)} and {@link #loadQuestions(String)}
     */
    public void clearQuestions() {
        questions.clear();
    }

    /**
     * Clears all loaded questions of the specified {@link Difficulty}.
     */
    public void clearQuestions(Difficulty difficulty) {
        List<Question> dQuestions = questions.get(difficulty);
        if (dQuestions != null)
            dQuestions.clear();
    }

}
